name: Update Browser Versions

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-ips:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: '8.4'
            extensions: mbstring

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
            path: ${{ steps.composer-cache.outputs.dir }}
            key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - run: composer install --no-interaction --prefer-dist --no-dev

      - name: Build
        run: php src/build.php
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'dist/*'
          commit_message: Updated browser versions
