name: Update Browser Versions

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-ips:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
            path: /tmp/composer-cache
            key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install Composer
        uses: php-actions/composer@v6
        with:
            php_version: 8.3
            php_extensions: mbstring xdebug

      - name: Build
        run: php src/build.php

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'dist/*'
          commit_message: Updated browser versions
